# Generated by Django 5.0.14 on 2025-11-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="kind",
            field=models.CharField(
                choices=[("quiz", "Quiz"), ("match", "Match")],
                default="quiz",
                max_length=20,
            ),
        ),
    ]
