# Generated by Django 5.0.14 on 2025-11-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="rating",
        ),
    ]
